"use node";

import { internalAction } from "./_generated/server";
import { v } from "convex/values";
import nodemailer from "nodemailer";
import { generateDocxFromMarkdown } from "../src/lib/GenerateDocx";
import { generateText } from "ai";
import { openai } from "@ai-sdk/openai";
import { api, internal } from "./_generated/api";

export const executeScheduler = internalAction({
  args: {
    projectId: v.id("projects"),
    recipientEmail: v.string(),
    schedulerName: v.string(),
    schedulerId: v.id("schedulers"),
  },
  handler: async (ctx, args) => {
    try {
      // Mark run as started
      await ctx.runMutation(internal.scheduler.markRunStarted, {
        schedulerId: args.schedulerId,
      });

      // 1. Fetch all data from Convex using our aggregator query
      console.log(
        `[Scheduler] Fetching context for project: ${args.projectId}`,
      );
      const context = await ctx.runQuery(
        api.scheduler.getProjectScheduleContext,
        {
          projectId: args.projectId,
        },
      );

      if (!context) {
        throw new Error("Project context not found");
      }

      // 2. Construct the prompt
      const prompt = `
You are "Kaya", an elite AI Project Manager and Scrum Master. Your goal is to provide a concise, high-impact Project Schedule Brief based on the provided data.

DATA CONTEXT:
${JSON.stringify(context, null, 2)}

INSTRUCTIONS:
1. Summarize the project's current health and timeline status.
2. Analyze the current sprint progress and highlight any bottlenecks.
3. Review team workload and identify potential burnout or under-utilization.
4. Call out CRITICAL and BLOCKED tasks/issues that need immediate attention.
5. Provide 3-5 strategic recommendations for the next few days.

OUTPUT FORMAT:
- Use clear Markdown formatting with titles and subtitles.
- Use bullet points for readability.
- Keep the tone professional, encouraging, and highly analytical.
- The document should be titled "Project Schedule Brief: ${context.insights.projectName}".

Begin the report:
`;

      // 3. Generate report via AI
      console.log(`[Scheduler] Generating brief with AI...`);
      const { text: reportMarkdown } = await generateText({
        model: openai("gpt-4.1-mini"),
        prompt: prompt,
      });
      console.log("[Scheduler] report generated");

      // 4. Generate docx using your existing function
      const docxBuffer = await generateDocxFromMarkdown(
        reportMarkdown,
        args.schedulerName,
      );
      console.log("[Scheduler] docx generated");

      // 5. Convert Markdown to HTML for a premium email feel
      const reportHtml = `
      <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1a1a1a; line-height: 1.6; max-width: 600px; margin: 20px auto; padding: 20px; border: 1px solid #e1e1e1; border-radius: 12px; background-color: #ffffff;">
        <h1 style="color: #6C47FF; font-size: 24px; border-bottom: 2px solid #f0f0f0; padding-bottom: 15px; margin-bottom: 25px; text-align: center;">📊 Project Schedule Brief</h1>
        ${reportMarkdown
          .replace(
            /^# (.*$)/gim,
            '<h1 style="color: #6C47FF; font-size: 22px;">$1</h1>',
          )
          .replace(
            /^## (.*$)/gim,
            '<h2 style="color: #2D2D2D; font-size: 18px; margin-top: 30px; border-left: 4px solid #6C47FF; padding-left: 10px;">$1</h2>',
          )
          .replace(
            /^### (.*$)/gim,
            '<h3 style="color: #4A4A4A; font-size: 16px; margin-top: 20px;">$1</h3>',
          )
          .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #000;">$1</strong>')
          .replace(/^- (.*$)/gim, '<li style="margin-bottom: 10px;">$1</li>')
          .replace(
            /^\d+\. (.*$)/gim,
            '<li style="margin-bottom: 10px;">$1</li>',
          )
          .split("\n")
          .filter((l) => l.trim() !== "")
          .map((l) =>
            l.startsWith("<") ? l : `<p style="margin-bottom: 15px;">${l}</p>`,
          )
          .join("")}
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #f0f0f0; text-align: center; color: #888; font-size: 12px;">
          <p>Generated by <strong>Kaya AI</strong> — Your Project Intelligence Partner</p>
        </div>
      </div>
    `;

      // 6. Send email with docx attached
      const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: process.env.EMAIL_USER || process.env.EMAIL,
          pass: process.env.EMAIL_PASS,
        },
      });

      await transporter.sendMail({
        from: `"Kaya" <${process.env.EMAIL_USER || process.env.EMAIL || "noreply@wekraft.com"}>`,
        to: args.recipientEmail,
        subject: `📊 ${args.schedulerName} — Project Report`,
        text: reportMarkdown,
        html: reportHtml,
        attachments: [
          {
            filename: `${args.schedulerName}-report.docx`,
            content: docxBuffer,
          },
        ],
      });
      console.log(`[Scheduler] email sent to ${args.recipientEmail}`);

      // 7. Mark as complete and update database (RECURSIVE)
      await ctx.runMutation(internal.scheduler.markRunCompleteAndScheduleNext, {
        schedulerId: args.schedulerId,
      });
    } catch (error: any) {
      console.error("[Scheduler] Error running scheduler:", error);
      // Ensure we reset the status so it can run again
      await ctx.runMutation(internal.scheduler.handleRunError, {
        schedulerId: args.schedulerId,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  },
});
