[project]
name = "wekraft-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "cohere>=7.1.1",
    "fastapi>=0.141.1",
    "langchain>=1.4.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.2",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "langgraph-checkpoint-postgres>=3.1.2",
    "langgraph-checkpoint-redis>=0.5.2",
    "langsmith>=0.12.1",
    "llama-cloud>=2.8",
    "pinecone>=10.0.0",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "redis>=8.1.0",
    "sse-starlette>=3.4.11",
    "structlog>=26.1.0",
    "temporalio>=1.32.0",
    "tenacity>=9.1.4",
    "uvicorn[standard]>=0.52.4",
]
